name: Periodic health check

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 10 * * *'
    
jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Scheduled Health check
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://pokedex-fso-cicd-practice-1110.herokuapp.com/health
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1          
      - name: Scheduled Health check Success notification to webhhook
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          description: The application 'pokedex-fso-cicd-practice-1110' passed scheduled health check
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Scheduled Health check Failure notification to webhhook
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          description: The application 'pokedex-fso-cicd-practice-1110' did not pass scheduled health check
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}